[build]
  publish = "public"

# Admin Portal Routing
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

# Supplier Portal Routing
[[redirects]]
  from = "/supplier"
  to = "/supplier/index.html"
  status = 200

[[redirects]]
  from = "/supplier/*"
  to = "/supplier/:splat"
  status = 200

# Fallback for main user single-page routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200